//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for adhocroot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adhocroot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Report" type="{http://www.prognoz.ru/Adhoc}report" minOccurs="0"/>
 *         &lt;element name="DataProviders" type="{http://www.prognoz.ru/Adhoc}dataproviders" minOccurs="0"/>
 *         &lt;element name="Themes" type="{http://www.prognoz.ru/Adhoc}themes" minOccurs="0"/>
 *         &lt;element name="Resources" type="{http://www.prognoz.ru/Adhoc}resources" minOccurs="0"/>
 *         &lt;element name="Components" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" fixed="0.83" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adhocroot", propOrder = {

})
public class Adhocroot {

    @XmlElement(name = "Report")
    protected Report report;
    @XmlElement(name = "DataProviders")
    protected Dataproviders dataProviders;
    @XmlElement(name = "Themes")
    protected Themes themes;
    @XmlElement(name = "Resources")
    protected Resources resources;
    @XmlElement(name = "Components")
    protected Object components;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link Report }
     *     
     */
    public Report getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link Report }
     *     
     */
    public void setReport(Report value) {
        this.report = value;
    }

    /**
     * Gets the value of the dataProviders property.
     * 
     * @return
     *     possible object is
     *     {@link Dataproviders }
     *     
     */
    public Dataproviders getDataProviders() {
        return dataProviders;
    }

    /**
     * Sets the value of the dataProviders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dataproviders }
     *     
     */
    public void setDataProviders(Dataproviders value) {
        this.dataProviders = value;
    }

    /**
     * Gets the value of the themes property.
     * 
     * @return
     *     possible object is
     *     {@link Themes }
     *     
     */
    public Themes getThemes() {
        return themes;
    }

    /**
     * Sets the value of the themes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Themes }
     *     
     */
    public void setThemes(Themes value) {
        this.themes = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link Resources }
     *     
     */
    public Resources getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resources }
     *     
     */
    public void setResources(Resources value) {
        this.resources = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setComponents(Object value) {
        this.components = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "0.83";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
