//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.neosoft.exjaxb.test.adhoc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for containerBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="containerBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="StackPanel" type="{http://www.prognoz.ru/Adhoc}stackPanel"/>
 *         &lt;element name="Grid" type="{http://www.prognoz.ru/Adhoc}grid"/>
 *         &lt;element name="PageControl" type="{http://www.prognoz.ru/Adhoc}pageControl"/>
 *         &lt;element name="ScrollViewer" type="{http://www.prognoz.ru/Adhoc}scrollViewer"/>
 *         &lt;element name="Container" type="{http://www.prognoz.ru/Adhoc}container"/>
 *         &lt;element name="DockPanel" type="{http://www.prognoz.ru/Adhoc}dockPanel"/>
 *         &lt;element name="DialogContainer" type="{http://www.prognoz.ru/Adhoc}dialogContainer"/>
 *         &lt;element name="Frame" type="{http://www.prognoz.ru/Adhoc}frame"/>
 *         &lt;element name="Legend" type="{http://www.prognoz.ru/Adhoc}legend"/>
 *         &lt;element name="Image" type="{http://www.prognoz.ru/Adhoc}image"/>
 *         &lt;element name="ComboBox" type="{http://www.prognoz.ru/Adhoc}comboBox"/>
 *         &lt;element name="TabControl" type="{http://www.prognoz.ru/Adhoc}tabControl"/>
 *         &lt;element name="Toolbar" type="{http://www.prognoz.ru/Adhoc}toolbar"/>
 *         &lt;element name="DatePicker" type="{http://www.prognoz.ru/Adhoc}datePicker"/>
 *         &lt;element name="Button" type="{http://www.prognoz.ru/Adhoc}button"/>
 *         &lt;element name="CheckBox" type="{http://www.prognoz.ru/Adhoc}checkBox"/>
 *         &lt;element name="RadioButton" type="{http://www.prognoz.ru/Adhoc}radioButton"/>
 *         &lt;element name="Menu" type="{http://www.prognoz.ru/Adhoc}menu"/>
 *         &lt;element name="SplitPanel" type="{http://www.prognoz.ru/Adhoc}splitPanel"/>
 *       &lt;/choice>
 *       &lt;attribute name="BackgroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VerticalSpacing" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="HorizontalSpacing" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="ThemeId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "containerBase", propOrder = {
    "stackPanelOrGridOrPageControl"
})
@XmlSeeAlso({
    DialogContainer.class,
    DockPanel.class,
    Container.class,
    PageControl.class,
    StackPanel.class,
    ScrollViewer.class
})
public class ContainerBase
    extends Obj
{

    @XmlElements({
        @XmlElement(name = "CheckBox", type = CheckBox.class),
        @XmlElement(name = "DatePicker", type = DatePicker.class),
        @XmlElement(name = "SplitPanel", type = SplitPanel.class),
        @XmlElement(name = "RadioButton", type = RadioButton.class),
        @XmlElement(name = "Grid", type = Grid.class),
        @XmlElement(name = "ScrollViewer", type = ScrollViewer.class),
        @XmlElement(name = "Frame", type = Frame.class),
        @XmlElement(name = "StackPanel", type = StackPanel.class),
        @XmlElement(name = "Button", type = Button.class),
        @XmlElement(name = "PageControl", type = PageControl.class),
        @XmlElement(name = "TabControl", type = TabControl.class),
        @XmlElement(name = "DialogContainer", type = DialogContainer.class),
        @XmlElement(name = "ComboBox", type = ComboBox.class),
        @XmlElement(name = "Toolbar", type = Toolbar.class),
        @XmlElement(name = "Menu", type = Menu.class),
        @XmlElement(name = "Container", type = Container.class),
        @XmlElement(name = "Image", type = Image.class),
        @XmlElement(name = "DockPanel", type = DockPanel.class),
        @XmlElement(name = "Legend", type = Legend.class)
    })
    protected List<Obj> stackPanelOrGridOrPageControl;
    @XmlAttribute(name = "BackgroundColor")
    protected String backgroundColor;
    @XmlAttribute(name = "VerticalSpacing")
    protected String verticalSpacing;
    @XmlAttribute(name = "HorizontalSpacing")
    protected String horizontalSpacing;
    @XmlAttribute(name = "ThemeId")
    protected String themeId;

    /**
     * Gets the value of the stackPanelOrGridOrPageControl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stackPanelOrGridOrPageControl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStackPanelOrGridOrPageControl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CheckBox }
     * {@link DatePicker }
     * {@link SplitPanel }
     * {@link RadioButton }
     * {@link Grid }
     * {@link ScrollViewer }
     * {@link Frame }
     * {@link StackPanel }
     * {@link Button }
     * {@link PageControl }
     * {@link TabControl }
     * {@link DialogContainer }
     * {@link ComboBox }
     * {@link Toolbar }
     * {@link Menu }
     * {@link Container }
     * {@link Image }
     * {@link DockPanel }
     * {@link Legend }
     * 
     * 
     */
    public List<Obj> getStackPanelOrGridOrPageControl() {
        if (stackPanelOrGridOrPageControl == null) {
            stackPanelOrGridOrPageControl = new ArrayList<Obj>();
        }
        return this.stackPanelOrGridOrPageControl;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

    /**
     * Gets the value of the verticalSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalSpacing() {
        if (verticalSpacing == null) {
            return "0";
        } else {
            return verticalSpacing;
        }
    }

    /**
     * Sets the value of the verticalSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalSpacing(String value) {
        this.verticalSpacing = value;
    }

    /**
     * Gets the value of the horizontalSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalSpacing() {
        if (horizontalSpacing == null) {
            return "0";
        } else {
            return horizontalSpacing;
        }
    }

    /**
     * Sets the value of the horizontalSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalSpacing(String value) {
        this.horizontalSpacing = value;
    }

    /**
     * Gets the value of the themeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThemeId() {
        return themeId;
    }

    /**
     * Sets the value of the themeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThemeId(String value) {
        this.themeId = value;
    }

}
