//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for control complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="control">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;element name="StackPanel" type="{http://www.prognoz.ru/Adhoc}stackPanel"/>
 *             &lt;element name="Grid" type="{http://www.prognoz.ru/Adhoc}grid"/>
 *             &lt;element name="PageControl" type="{http://www.prognoz.ru/Adhoc}pageControl"/>
 *             &lt;element name="ScrollViewer" type="{http://www.prognoz.ru/Adhoc}scrollViewer"/>
 *             &lt;element name="Container" type="{http://www.prognoz.ru/Adhoc}container"/>
 *             &lt;element name="DockPanel" type="{http://www.prognoz.ru/Adhoc}dockPanel"/>
 *             &lt;element name="DialogContainer" type="{http://www.prognoz.ru/Adhoc}dialogContainer"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Frame" type="{http://www.prognoz.ru/Adhoc}frame"/>
 *           &lt;element name="Legend" type="{http://www.prognoz.ru/Adhoc}legend"/>
 *           &lt;element name="Image" type="{http://www.prognoz.ru/Adhoc}image"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="ComboBox" type="{http://www.prognoz.ru/Adhoc}comboBox"/>
 *           &lt;element name="TabControl" type="{http://www.prognoz.ru/Adhoc}tabControl"/>
 *           &lt;element name="Toolbar" type="{http://www.prognoz.ru/Adhoc}toolbar"/>
 *           &lt;element name="DatePicker" type="{http://www.prognoz.ru/Adhoc}datePicker"/>
 *           &lt;element name="Button" type="{http://www.prognoz.ru/Adhoc}button"/>
 *           &lt;element name="CheckBox" type="{http://www.prognoz.ru/Adhoc}checkBox"/>
 *           &lt;element name="RadioButton" type="{http://www.prognoz.ru/Adhoc}radioButton"/>
 *           &lt;element name="Menu" type="{http://www.prognoz.ru/Adhoc}menu"/>
 *           &lt;element name="SplitPanel" type="{http://www.prognoz.ru/Adhoc}splitPanel"/>
 *         &lt;/choice>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "control", propOrder = {
    "stackPanelOrGridOrPageControl",
    "frameOrLegendOrImage",
    "comboBoxOrTabControlOrToolbar"
})
@XmlSeeAlso({
    DatePicker.class,
    Toolbar.class,
    SplitPanel.class,
    Button.class,
    Menu.class,
    RadioButton.class,
    TabControl.class,
    ComboBox.class,
    CheckBox.class
})
public class Control
    extends Obj
{

    @XmlElements({
        @XmlElement(name = "StackPanel", type = StackPanel.class),
        @XmlElement(name = "DockPanel", type = DockPanel.class),
        @XmlElement(name = "Grid", type = Grid.class),
        @XmlElement(name = "DialogContainer", type = DialogContainer.class),
        @XmlElement(name = "Container", type = Container.class),
        @XmlElement(name = "ScrollViewer", type = ScrollViewer.class),
        @XmlElement(name = "PageControl", type = PageControl.class)
    })
    protected List<Obj> stackPanelOrGridOrPageControl;
    @XmlElements({
        @XmlElement(name = "Legend", type = Legend.class),
        @XmlElement(name = "Frame", type = Frame.class),
        @XmlElement(name = "Image", type = Image.class)
    })
    protected List<Infoblock> frameOrLegendOrImage;
    @XmlElements({
        @XmlElement(name = "Toolbar", type = Toolbar.class),
        @XmlElement(name = "CheckBox", type = CheckBox.class),
        @XmlElement(name = "RadioButton", type = RadioButton.class),
        @XmlElement(name = "DatePicker", type = DatePicker.class),
        @XmlElement(name = "SplitPanel", type = SplitPanel.class),
        @XmlElement(name = "Menu", type = Menu.class),
        @XmlElement(name = "TabControl", type = TabControl.class),
        @XmlElement(name = "Button", type = Button.class),
        @XmlElement(name = "ComboBox", type = ComboBox.class)
    })
    protected List<Control> comboBoxOrTabControlOrToolbar;

    /**
     * Gets the value of the stackPanelOrGridOrPageControl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stackPanelOrGridOrPageControl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStackPanelOrGridOrPageControl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StackPanel }
     * {@link DockPanel }
     * {@link Grid }
     * {@link DialogContainer }
     * {@link Container }
     * {@link ScrollViewer }
     * {@link PageControl }
     * 
     * 
     */
    public List<Obj> getStackPanelOrGridOrPageControl() {
        if (stackPanelOrGridOrPageControl == null) {
            stackPanelOrGridOrPageControl = new ArrayList<Obj>();
        }
        return this.stackPanelOrGridOrPageControl;
    }

    /**
     * Gets the value of the frameOrLegendOrImage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frameOrLegendOrImage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrameOrLegendOrImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Legend }
     * {@link Frame }
     * {@link Image }
     * 
     * 
     */
    public List<Infoblock> getFrameOrLegendOrImage() {
        if (frameOrLegendOrImage == null) {
            frameOrLegendOrImage = new ArrayList<Infoblock>();
        }
        return this.frameOrLegendOrImage;
    }

    /**
     * Gets the value of the comboBoxOrTabControlOrToolbar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comboBoxOrTabControlOrToolbar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComboBoxOrTabControlOrToolbar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Toolbar }
     * {@link CheckBox }
     * {@link RadioButton }
     * {@link DatePicker }
     * {@link SplitPanel }
     * {@link Menu }
     * {@link TabControl }
     * {@link Button }
     * {@link ComboBox }
     * 
     * 
     */
    public List<Control> getComboBoxOrTabControlOrToolbar() {
        if (comboBoxOrTabControlOrToolbar == null) {
            comboBoxOrTabControlOrToolbar = new ArrayList<Control>();
        }
        return this.comboBoxOrTabControlOrToolbar;
    }

}
