//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for container complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="container">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}containerBase">
 *       &lt;sequence>
 *         &lt;element name="Container.Caption" type="{http://www.prognoz.ru/Adhoc}tag.caption"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "container", propOrder = {
    "containerCaption"
})
public class Container
    extends ContainerBase
{

    @XmlElement(name = "Container.Caption", required = true)
    protected TagCaption containerCaption;

    /**
     * Gets the value of the containerCaption property.
     * 
     * @return
     *     possible object is
     *     {@link TagCaption }
     *     
     */
    public TagCaption getContainerCaption() {
        return containerCaption;
    }

    /**
     * Sets the value of the containerCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagCaption }
     *     
     */
    public void setContainerCaption(TagCaption value) {
        this.containerCaption = value;
    }

}
