//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.neosoft.exjaxb.test.adhoc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataproviders complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataproviders">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="DataSources">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="P5SqlDataSource" type="{http://www.prognoz.ru/Adhoc}ds.p5sql"/>
 *                   &lt;element name="P5ExpressReportDataSource" type="{http://www.prognoz.ru/Adhoc}ds.p5expressreport"/>
 *                   &lt;element name="P5ProceduralReportDataSource" type="{http://www.prognoz.ru/Adhoc}ds.p5proceduralreport"/>
 *                   &lt;element name="OracleDataSource" type="{http://www.prognoz.ru/Adhoc}ds.ora"/>
 *                   &lt;element name="MsSqlDataSource" type="{http://www.prognoz.ru/Adhoc}ds.mssql"/>
 *                   &lt;element name="TextDataSource" type="{http://www.prognoz.ru/Adhoc}ds.text"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Connections">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="P5MetabaseConnection" type="{http://www.prognoz.ru/Adhoc}connect.p5mb"/>
 *                     &lt;element name="OraConnection" type="{http://www.prognoz.ru/Adhoc}connect.ora"/>
 *                     &lt;element name="MSSQLConnection" type="{http://www.prognoz.ru/Adhoc}connect.mssql"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataproviders", propOrder = {

})
public class Dataproviders {

    @XmlElement(name = "DataSources", required = true)
    protected Dataproviders.DataSources dataSources;
    @XmlElement(name = "Connections", required = true)
    protected Dataproviders.Connections connections;

    /**
     * Gets the value of the dataSources property.
     * 
     * @return
     *     possible object is
     *     {@link Dataproviders.DataSources }
     *     
     */
    public Dataproviders.DataSources getDataSources() {
        return dataSources;
    }

    /**
     * Sets the value of the dataSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dataproviders.DataSources }
     *     
     */
    public void setDataSources(Dataproviders.DataSources value) {
        this.dataSources = value;
    }

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link Dataproviders.Connections }
     *     
     */
    public Dataproviders.Connections getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dataproviders.Connections }
     *     
     */
    public void setConnections(Dataproviders.Connections value) {
        this.connections = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="P5MetabaseConnection" type="{http://www.prognoz.ru/Adhoc}connect.p5mb"/>
     *           &lt;element name="OraConnection" type="{http://www.prognoz.ru/Adhoc}connect.ora"/>
     *           &lt;element name="MSSQLConnection" type="{http://www.prognoz.ru/Adhoc}connect.mssql"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p5MetabaseConnectionOrOraConnectionOrMSSQLConnection"
    })
    public static class Connections {

        @XmlElements({
            @XmlElement(name = "OraConnection", type = ConnectOra.class),
            @XmlElement(name = "P5MetabaseConnection", type = ConnectP5Mb.class),
            @XmlElement(name = "MSSQLConnection", type = ConnectMssql.class)
        })
        protected List<ConnectGeneric> p5MetabaseConnectionOrOraConnectionOrMSSQLConnection;

        /**
         * Gets the value of the p5MetabaseConnectionOrOraConnectionOrMSSQLConnection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p5MetabaseConnectionOrOraConnectionOrMSSQLConnection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP5MetabaseConnectionOrOraConnectionOrMSSQLConnection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConnectOra }
         * {@link ConnectP5Mb }
         * {@link ConnectMssql }
         * 
         * 
         */
        public List<ConnectGeneric> getP5MetabaseConnectionOrOraConnectionOrMSSQLConnection() {
            if (p5MetabaseConnectionOrOraConnectionOrMSSQLConnection == null) {
                p5MetabaseConnectionOrOraConnectionOrMSSQLConnection = new ArrayList<ConnectGeneric>();
            }
            return this.p5MetabaseConnectionOrOraConnectionOrMSSQLConnection;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="P5SqlDataSource" type="{http://www.prognoz.ru/Adhoc}ds.p5sql"/>
     *         &lt;element name="P5ExpressReportDataSource" type="{http://www.prognoz.ru/Adhoc}ds.p5expressreport"/>
     *         &lt;element name="P5ProceduralReportDataSource" type="{http://www.prognoz.ru/Adhoc}ds.p5proceduralreport"/>
     *         &lt;element name="OracleDataSource" type="{http://www.prognoz.ru/Adhoc}ds.ora"/>
     *         &lt;element name="MsSqlDataSource" type="{http://www.prognoz.ru/Adhoc}ds.mssql"/>
     *         &lt;element name="TextDataSource" type="{http://www.prognoz.ru/Adhoc}ds.text"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource"
    })
    public static class DataSources {

        @XmlElements({
            @XmlElement(name = "P5ProceduralReportDataSource", type = DsP5Proceduralreport.class),
            @XmlElement(name = "P5ExpressReportDataSource", type = DsP5Expressreport.class),
            @XmlElement(name = "MsSqlDataSource", type = DsMssql.class),
            @XmlElement(name = "OracleDataSource", type = DsOra.class),
            @XmlElement(name = "TextDataSource", type = DsText.class),
            @XmlElement(name = "P5SqlDataSource", type = DsP5Sql.class)
        })
        protected List<DsGeneric> p5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource;

        /**
         * Gets the value of the p5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DsP5Proceduralreport }
         * {@link DsP5Expressreport }
         * {@link DsMssql }
         * {@link DsOra }
         * {@link DsText }
         * {@link DsP5Sql }
         * 
         * 
         */
        public List<DsGeneric> getP5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource() {
            if (p5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource == null) {
                p5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource = new ArrayList<DsGeneric>();
            }
            return this.p5SqlDataSourceOrP5ExpressReportDataSourceOrP5ProceduralReportDataSource;
        }

    }

}
