//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.neosoft.exjaxb.test.adhoc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datePicker complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datePicker">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}control">
 *       &lt;attribute name="SelectedDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NumberOfMonths" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datePicker")
public class DatePicker
    extends Control
{

    @XmlAttribute(name = "SelectedDate")
    protected String selectedDate;
    @XmlAttribute(name = "NumberOfMonths")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger numberOfMonths;

    /**
     * Gets the value of the selectedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedDate() {
        return selectedDate;
    }

    /**
     * Sets the value of the selectedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedDate(String value) {
        this.selectedDate = value;
    }

    /**
     * Gets the value of the numberOfMonths property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfMonths() {
        return numberOfMonths;
    }

    /**
     * Sets the value of the numberOfMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfMonths(BigInteger value) {
        this.numberOfMonths = value;
    }

}
