//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.neosoft.exjaxb.test.adhoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ds.ora complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ds.ora">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}ds.generic">
 *       &lt;sequence>
 *         &lt;element name="OracleDataSource.Sql" type="{http://www.prognoz.ru/Adhoc}ds.ora.sql"/>
 *         &lt;element name="OracleDataSource.DataSourceParams" type="{http://www.prognoz.ru/Adhoc}ds.dsparams"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ds.ora", propOrder = {
    "oracleDataSourceSql",
    "oracleDataSourceDataSourceParams"
})
@XmlSeeAlso({
    DsP5Sql.class
})
public class DsOra
    extends DsGeneric
{

    @XmlElement(name = "OracleDataSource.Sql", required = true)
    protected DsOraSql oracleDataSourceSql;
    @XmlElement(name = "OracleDataSource.DataSourceParams", required = true)
    protected DsDsparams oracleDataSourceDataSourceParams;

    /**
     * Gets the value of the oracleDataSourceSql property.
     * 
     * @return
     *     possible object is
     *     {@link DsOraSql }
     *     
     */
    public DsOraSql getOracleDataSourceSql() {
        return oracleDataSourceSql;
    }

    /**
     * Sets the value of the oracleDataSourceSql property.
     * 
     * @param value
     *     allowed object is
     *     {@link DsOraSql }
     *     
     */
    public void setOracleDataSourceSql(DsOraSql value) {
        this.oracleDataSourceSql = value;
    }

    /**
     * Gets the value of the oracleDataSourceDataSourceParams property.
     * 
     * @return
     *     possible object is
     *     {@link DsDsparams }
     *     
     */
    public DsDsparams getOracleDataSourceDataSourceParams() {
        return oracleDataSourceDataSourceParams;
    }

    /**
     * Sets the value of the oracleDataSourceDataSourceParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link DsDsparams }
     *     
     */
    public void setOracleDataSourceDataSourceParams(DsDsparams value) {
        this.oracleDataSourceDataSourceParams = value;
    }

}
