//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ds.p5expressreport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ds.p5expressreport">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}ds.generic">
 *       &lt;sequence>
 *         &lt;element name="P5ExpressReportDataSource.DataSourceParams" type="{http://www.prognoz.ru/Adhoc}ds.dsparams"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MetabaseObjectId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MetabaseObjectKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ds.p5expressreport", propOrder = {
    "p5ExpressReportDataSourceDataSourceParams"
})
public class DsP5Expressreport
    extends DsGeneric
{

    @XmlElement(name = "P5ExpressReportDataSource.DataSourceParams", required = true)
    protected DsDsparams p5ExpressReportDataSourceDataSourceParams;
    @XmlAttribute(name = "MetabaseObjectId")
    protected String metabaseObjectId;
    @XmlAttribute(name = "MetabaseObjectKey")
    protected String metabaseObjectKey;

    /**
     * Gets the value of the p5ExpressReportDataSourceDataSourceParams property.
     * 
     * @return
     *     possible object is
     *     {@link DsDsparams }
     *     
     */
    public DsDsparams getP5ExpressReportDataSourceDataSourceParams() {
        return p5ExpressReportDataSourceDataSourceParams;
    }

    /**
     * Sets the value of the p5ExpressReportDataSourceDataSourceParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link DsDsparams }
     *     
     */
    public void setP5ExpressReportDataSourceDataSourceParams(DsDsparams value) {
        this.p5ExpressReportDataSourceDataSourceParams = value;
    }

    /**
     * Gets the value of the metabaseObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetabaseObjectId() {
        return metabaseObjectId;
    }

    /**
     * Sets the value of the metabaseObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetabaseObjectId(String value) {
        this.metabaseObjectId = value;
    }

    /**
     * Gets the value of the metabaseObjectKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetabaseObjectKey() {
        return metabaseObjectKey;
    }

    /**
     * Sets the value of the metabaseObjectKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetabaseObjectKey(String value) {
        this.metabaseObjectKey = value;
    }

}
