//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for frame complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="frame">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}infoblock">
 *       &lt;sequence>
 *         &lt;element name="Frame.Caption">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Caption">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
 *                           &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" default="CaptionText" />
 *                           &lt;attribute name="SubText" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *                           &lt;attribute name="VisibleText" type="{http://www.prognoz.ru/Adhoc}bool" default="True" />
 *                           &lt;attribute name="VisibleSubText" type="{http://www.prognoz.ru/Adhoc}bool" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Frame.DataSourceBinding" type="{http://www.prognoz.ru/Adhoc}frame.dataSourceBinding"/>
 *         &lt;element name="Frame.Visualizers" type="{http://www.prognoz.ru/Adhoc}infoblock.visualizers"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CurrentVisualizerId" type="{http://www.prognoz.ru/Adhoc}idType" default="" />
 *       &lt;attribute name="Expandable" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
 *       &lt;attribute name="RoundCorners" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
 *       &lt;attribute name="CaptionBackgroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ThemeId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Caption" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "frame", propOrder = {
    "frameCaption",
    "frameDataSourceBinding",
    "frameVisualizers"
})
public class Frame
    extends Infoblock
{

    @XmlElement(name = "Frame.Caption", required = true)
    protected Frame.FrameCaption frameCaption;
    @XmlElement(name = "Frame.DataSourceBinding", required = true)
    protected FrameDataSourceBinding frameDataSourceBinding;
    @XmlElement(name = "Frame.Visualizers", required = true)
    protected InfoblockVisualizers frameVisualizers;
    @XmlAttribute(name = "CurrentVisualizerId")
    protected String currentVisualizerId;
    @XmlAttribute(name = "Expandable")
    protected String expandable;
    @XmlAttribute(name = "RoundCorners")
    protected String roundCorners;
    @XmlAttribute(name = "CaptionBackgroundColor")
    protected String captionBackgroundColor;
    @XmlAttribute(name = "ThemeId")
    protected String themeId;
    @XmlAttribute(name = "Caption")
    protected String caption;

    /**
     * Gets the value of the frameCaption property.
     * 
     * @return
     *     possible object is
     *     {@link Frame.FrameCaption }
     *     
     */
    public Frame.FrameCaption getFrameCaption() {
        return frameCaption;
    }

    /**
     * Sets the value of the frameCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frame.FrameCaption }
     *     
     */
    public void setFrameCaption(Frame.FrameCaption value) {
        this.frameCaption = value;
    }

    /**
     * Gets the value of the frameDataSourceBinding property.
     * 
     * @return
     *     possible object is
     *     {@link FrameDataSourceBinding }
     *     
     */
    public FrameDataSourceBinding getFrameDataSourceBinding() {
        return frameDataSourceBinding;
    }

    /**
     * Sets the value of the frameDataSourceBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrameDataSourceBinding }
     *     
     */
    public void setFrameDataSourceBinding(FrameDataSourceBinding value) {
        this.frameDataSourceBinding = value;
    }

    /**
     * Gets the value of the frameVisualizers property.
     * 
     * @return
     *     possible object is
     *     {@link InfoblockVisualizers }
     *     
     */
    public InfoblockVisualizers getFrameVisualizers() {
        return frameVisualizers;
    }

    /**
     * Sets the value of the frameVisualizers property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoblockVisualizers }
     *     
     */
    public void setFrameVisualizers(InfoblockVisualizers value) {
        this.frameVisualizers = value;
    }

    /**
     * Gets the value of the currentVisualizerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentVisualizerId() {
        if (currentVisualizerId == null) {
            return "";
        } else {
            return currentVisualizerId;
        }
    }

    /**
     * Sets the value of the currentVisualizerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentVisualizerId(String value) {
        this.currentVisualizerId = value;
    }

    /**
     * Gets the value of the expandable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpandable() {
        if (expandable == null) {
            return "false";
        } else {
            return expandable;
        }
    }

    /**
     * Sets the value of the expandable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpandable(String value) {
        this.expandable = value;
    }

    /**
     * Gets the value of the roundCorners property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoundCorners() {
        if (roundCorners == null) {
            return "false";
        } else {
            return roundCorners;
        }
    }

    /**
     * Sets the value of the roundCorners property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoundCorners(String value) {
        this.roundCorners = value;
    }

    /**
     * Gets the value of the captionBackgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionBackgroundColor() {
        return captionBackgroundColor;
    }

    /**
     * Sets the value of the captionBackgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionBackgroundColor(String value) {
        this.captionBackgroundColor = value;
    }

    /**
     * Gets the value of the themeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThemeId() {
        return themeId;
    }

    /**
     * Sets the value of the themeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThemeId(String value) {
        this.themeId = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Caption">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
     *                 &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" default="CaptionText" />
     *                 &lt;attribute name="SubText" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
     *                 &lt;attribute name="VisibleText" type="{http://www.prognoz.ru/Adhoc}bool" default="True" />
     *                 &lt;attribute name="VisibleSubText" type="{http://www.prognoz.ru/Adhoc}bool" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caption"
    })
    public static class FrameCaption {

        @XmlElement(name = "Caption", required = true)
        protected Frame.FrameCaption.Caption caption;

        /**
         * Gets the value of the caption property.
         * 
         * @return
         *     possible object is
         *     {@link Frame.FrameCaption.Caption }
         *     
         */
        public Frame.FrameCaption.Caption getCaption() {
            return caption;
        }

        /**
         * Sets the value of the caption property.
         * 
         * @param value
         *     allowed object is
         *     {@link Frame.FrameCaption.Caption }
         *     
         */
        public void setCaption(Frame.FrameCaption.Caption value) {
            this.caption = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
         *       &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" default="CaptionText" />
         *       &lt;attribute name="SubText" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
         *       &lt;attribute name="VisibleText" type="{http://www.prognoz.ru/Adhoc}bool" default="True" />
         *       &lt;attribute name="VisibleSubText" type="{http://www.prognoz.ru/Adhoc}bool" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Caption
            extends Obj
        {

            @XmlAttribute(name = "Text")
            protected String text;
            @XmlAttribute(name = "SubText")
            protected String subText;
            @XmlAttribute(name = "VisibleText")
            protected String visibleText;
            @XmlAttribute(name = "VisibleSubText")
            protected String visibleSubText;

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                if (text == null) {
                    return "CaptionText";
                } else {
                    return text;
                }
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }

            /**
             * Gets the value of the subText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubText() {
                if (subText == null) {
                    return "";
                } else {
                    return subText;
                }
            }

            /**
             * Sets the value of the subText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubText(String value) {
                this.subText = value;
            }

            /**
             * Gets the value of the visibleText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVisibleText() {
                if (visibleText == null) {
                    return "True";
                } else {
                    return visibleText;
                }
            }

            /**
             * Sets the value of the visibleText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVisibleText(String value) {
                this.visibleText = value;
            }

            /**
             * Gets the value of the visibleSubText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVisibleSubText() {
                return visibleSubText;
            }

            /**
             * Sets the value of the visibleSubText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVisibleSubText(String value) {
                this.visibleSubText = value;
            }

        }

    }

}
