//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for frame.dataSourceBinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="frame.dataSourceBinding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="DataSourceBinding">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Param" type="{http://www.prognoz.ru/Adhoc}dsb.param" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="DataSourceId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "frame.dataSourceBinding", propOrder = {
    "dataSourceBinding"
})
public class FrameDataSourceBinding {

    @XmlElement(name = "DataSourceBinding")
    protected FrameDataSourceBinding.DataSourceBinding dataSourceBinding;

    /**
     * Gets the value of the dataSourceBinding property.
     * 
     * @return
     *     possible object is
     *     {@link FrameDataSourceBinding.DataSourceBinding }
     *     
     */
    public FrameDataSourceBinding.DataSourceBinding getDataSourceBinding() {
        return dataSourceBinding;
    }

    /**
     * Sets the value of the dataSourceBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrameDataSourceBinding.DataSourceBinding }
     *     
     */
    public void setDataSourceBinding(FrameDataSourceBinding.DataSourceBinding value) {
        this.dataSourceBinding = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Param" type="{http://www.prognoz.ru/Adhoc}dsb.param" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="DataSourceId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "param"
    })
    public static class DataSourceBinding {

        @XmlElement(name = "Param")
        protected DsbParam param;
        @XmlAttribute(name = "DataSourceId", required = true)
        protected String dataSourceId;

        /**
         * Gets the value of the param property.
         * 
         * @return
         *     possible object is
         *     {@link DsbParam }
         *     
         */
        public DsbParam getParam() {
            return param;
        }

        /**
         * Sets the value of the param property.
         * 
         * @param value
         *     allowed object is
         *     {@link DsbParam }
         *     
         */
        public void setParam(DsbParam value) {
            this.param = value;
        }

        /**
         * Gets the value of the dataSourceId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataSourceId() {
            return dataSourceId;
        }

        /**
         * Sets the value of the dataSourceId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataSourceId(String value) {
            this.dataSourceId = value;
        }

    }

}
