//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for grid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="grid">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="Grid.ColumnDefinitions">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="ColumnDefinitions">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="ColumnDefinition" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="Width" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                       &lt;attribute name="MinWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Grid.RowDefinitions">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="RowDefinitions">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="RowDefinition" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="Height" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                       &lt;attribute name="MinHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;element name="StackPanel" type="{http://www.prognoz.ru/Adhoc}stackPanel"/>
 *             &lt;element name="Grid" type="{http://www.prognoz.ru/Adhoc}grid"/>
 *             &lt;element name="PageControl" type="{http://www.prognoz.ru/Adhoc}pageControl"/>
 *             &lt;element name="ScrollViewer" type="{http://www.prognoz.ru/Adhoc}scrollViewer"/>
 *             &lt;element name="Container" type="{http://www.prognoz.ru/Adhoc}container"/>
 *             &lt;element name="DockPanel" type="{http://www.prognoz.ru/Adhoc}dockPanel"/>
 *             &lt;element name="DialogContainer" type="{http://www.prognoz.ru/Adhoc}dialogContainer"/>
 *             &lt;element name="Frame" type="{http://www.prognoz.ru/Adhoc}frame"/>
 *             &lt;element name="Legend" type="{http://www.prognoz.ru/Adhoc}legend"/>
 *             &lt;element name="Image" type="{http://www.prognoz.ru/Adhoc}image"/>
 *             &lt;element name="ComboBox" type="{http://www.prognoz.ru/Adhoc}comboBox"/>
 *             &lt;element name="TabControl" type="{http://www.prognoz.ru/Adhoc}tabControl"/>
 *             &lt;element name="Toolbar" type="{http://www.prognoz.ru/Adhoc}toolbar"/>
 *             &lt;element name="DatePicker" type="{http://www.prognoz.ru/Adhoc}datePicker"/>
 *             &lt;element name="Button" type="{http://www.prognoz.ru/Adhoc}button"/>
 *             &lt;element name="CheckBox" type="{http://www.prognoz.ru/Adhoc}checkBox"/>
 *             &lt;element name="RadioButton" type="{http://www.prognoz.ru/Adhoc}radioButton"/>
 *             &lt;element name="Menu" type="{http://www.prognoz.ru/Adhoc}menu"/>
 *             &lt;element name="SplitPanel" type="{http://www.prognoz.ru/Adhoc}splitPanel"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="BackgroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VerticalSpacing" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="HorizontalSpacing" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="ThemeId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grid", propOrder = {
    "gridColumnDefinitionsOrGridRowDefinitionsOrStackPanel"
})
public class Grid
    extends Obj
{

    @XmlElements({
        @XmlElement(name = "PageControl", type = PageControl.class),
        @XmlElement(name = "Legend", type = Legend.class),
        @XmlElement(name = "SplitPanel", type = SplitPanel.class),
        @XmlElement(name = "DockPanel", type = DockPanel.class),
        @XmlElement(name = "DatePicker", type = DatePicker.class),
        @XmlElement(name = "ComboBox", type = ComboBox.class),
        @XmlElement(name = "RadioButton", type = RadioButton.class),
        @XmlElement(name = "Grid.ColumnDefinitions", type = Grid.GridColumnDefinitions.class),
        @XmlElement(name = "StackPanel", type = StackPanel.class),
        @XmlElement(name = "Button", type = Button.class),
        @XmlElement(name = "Menu", type = Menu.class),
        @XmlElement(name = "ScrollViewer", type = ScrollViewer.class),
        @XmlElement(name = "TabControl", type = TabControl.class),
        @XmlElement(name = "Image", type = Image.class),
        @XmlElement(name = "Grid.RowDefinitions", type = Grid.GridRowDefinitions.class),
        @XmlElement(name = "CheckBox", type = CheckBox.class),
        @XmlElement(name = "Toolbar", type = Toolbar.class),
        @XmlElement(name = "Frame", type = Frame.class),
        @XmlElement(name = "Container", type = Container.class),
        @XmlElement(name = "Grid", type = Grid.class),
        @XmlElement(name = "DialogContainer", type = DialogContainer.class)
    })
    protected List<Object> gridColumnDefinitionsOrGridRowDefinitionsOrStackPanel;
    @XmlAttribute(name = "BackgroundColor")
    protected String backgroundColor;
    @XmlAttribute(name = "VerticalSpacing")
    protected String verticalSpacing;
    @XmlAttribute(name = "HorizontalSpacing")
    protected String horizontalSpacing;
    @XmlAttribute(name = "ThemeId")
    protected String themeId;

    /**
     * Gets the value of the gridColumnDefinitionsOrGridRowDefinitionsOrStackPanel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gridColumnDefinitionsOrGridRowDefinitionsOrStackPanel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGridColumnDefinitionsOrGridRowDefinitionsOrStackPanel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PageControl }
     * {@link Legend }
     * {@link SplitPanel }
     * {@link DockPanel }
     * {@link DatePicker }
     * {@link ComboBox }
     * {@link RadioButton }
     * {@link Grid.GridColumnDefinitions }
     * {@link StackPanel }
     * {@link Button }
     * {@link Menu }
     * {@link ScrollViewer }
     * {@link TabControl }
     * {@link Image }
     * {@link Grid.GridRowDefinitions }
     * {@link CheckBox }
     * {@link Toolbar }
     * {@link Frame }
     * {@link Container }
     * {@link Grid }
     * {@link DialogContainer }
     * 
     * 
     */
    public List<Object> getGridColumnDefinitionsOrGridRowDefinitionsOrStackPanel() {
        if (gridColumnDefinitionsOrGridRowDefinitionsOrStackPanel == null) {
            gridColumnDefinitionsOrGridRowDefinitionsOrStackPanel = new ArrayList<Object>();
        }
        return this.gridColumnDefinitionsOrGridRowDefinitionsOrStackPanel;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

    /**
     * Gets the value of the verticalSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalSpacing() {
        if (verticalSpacing == null) {
            return "0";
        } else {
            return verticalSpacing;
        }
    }

    /**
     * Sets the value of the verticalSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalSpacing(String value) {
        this.verticalSpacing = value;
    }

    /**
     * Gets the value of the horizontalSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalSpacing() {
        if (horizontalSpacing == null) {
            return "0";
        } else {
            return horizontalSpacing;
        }
    }

    /**
     * Sets the value of the horizontalSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalSpacing(String value) {
        this.horizontalSpacing = value;
    }

    /**
     * Gets the value of the themeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThemeId() {
        return themeId;
    }

    /**
     * Sets the value of the themeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThemeId(String value) {
        this.themeId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ColumnDefinitions">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ColumnDefinition" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Width" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="MinWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "columnDefinitions"
    })
    public static class GridColumnDefinitions {

        @XmlElement(name = "ColumnDefinitions", required = true)
        protected Grid.GridColumnDefinitions.ColumnDefinitions columnDefinitions;

        /**
         * Gets the value of the columnDefinitions property.
         * 
         * @return
         *     possible object is
         *     {@link Grid.GridColumnDefinitions.ColumnDefinitions }
         *     
         */
        public Grid.GridColumnDefinitions.ColumnDefinitions getColumnDefinitions() {
            return columnDefinitions;
        }

        /**
         * Sets the value of the columnDefinitions property.
         * 
         * @param value
         *     allowed object is
         *     {@link Grid.GridColumnDefinitions.ColumnDefinitions }
         *     
         */
        public void setColumnDefinitions(Grid.GridColumnDefinitions.ColumnDefinitions value) {
            this.columnDefinitions = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ColumnDefinition" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Width" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="MinWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "columnDefinition"
        })
        public static class ColumnDefinitions {

            @XmlElement(name = "ColumnDefinition", required = true)
            protected List<Grid.GridColumnDefinitions.ColumnDefinitions.ColumnDefinition> columnDefinition;

            /**
             * Gets the value of the columnDefinition property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the columnDefinition property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumnDefinition().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Grid.GridColumnDefinitions.ColumnDefinitions.ColumnDefinition }
             * 
             * 
             */
            public List<Grid.GridColumnDefinitions.ColumnDefinitions.ColumnDefinition> getColumnDefinition() {
                if (columnDefinition == null) {
                    columnDefinition = new ArrayList<Grid.GridColumnDefinitions.ColumnDefinitions.ColumnDefinition>();
                }
                return this.columnDefinition;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Width" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="MinWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ColumnDefinition {

                @XmlAttribute(name = "Width", required = true)
                protected String width;
                @XmlAttribute(name = "MinWidth", required = true)
                protected String minWidth;

                /**
                 * Gets the value of the width property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWidth(String value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the minWidth property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinWidth() {
                    return minWidth;
                }

                /**
                 * Sets the value of the minWidth property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinWidth(String value) {
                    this.minWidth = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RowDefinitions">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RowDefinition" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Height" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="MinHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rowDefinitions"
    })
    public static class GridRowDefinitions {

        @XmlElement(name = "RowDefinitions", required = true)
        protected Grid.GridRowDefinitions.RowDefinitions rowDefinitions;

        /**
         * Gets the value of the rowDefinitions property.
         * 
         * @return
         *     possible object is
         *     {@link Grid.GridRowDefinitions.RowDefinitions }
         *     
         */
        public Grid.GridRowDefinitions.RowDefinitions getRowDefinitions() {
            return rowDefinitions;
        }

        /**
         * Sets the value of the rowDefinitions property.
         * 
         * @param value
         *     allowed object is
         *     {@link Grid.GridRowDefinitions.RowDefinitions }
         *     
         */
        public void setRowDefinitions(Grid.GridRowDefinitions.RowDefinitions value) {
            this.rowDefinitions = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RowDefinition" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Height" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="MinHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rowDefinition"
        })
        public static class RowDefinitions {

            @XmlElement(name = "RowDefinition", required = true)
            protected List<Grid.GridRowDefinitions.RowDefinitions.RowDefinition> rowDefinition;

            /**
             * Gets the value of the rowDefinition property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the rowDefinition property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRowDefinition().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Grid.GridRowDefinitions.RowDefinitions.RowDefinition }
             * 
             * 
             */
            public List<Grid.GridRowDefinitions.RowDefinitions.RowDefinition> getRowDefinition() {
                if (rowDefinition == null) {
                    rowDefinition = new ArrayList<Grid.GridRowDefinitions.RowDefinitions.RowDefinition>();
                }
                return this.rowDefinition;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Height" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="MinHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class RowDefinition {

                @XmlAttribute(name = "Height", required = true)
                protected String height;
                @XmlAttribute(name = "MinHeight", required = true)
                protected String minHeight;

                /**
                 * Gets the value of the height property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHeight(String value) {
                    this.height = value;
                }

                /**
                 * Gets the value of the minHeight property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinHeight() {
                    return minHeight;
                }

                /**
                 * Sets the value of the minHeight property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinHeight(String value) {
                    this.minHeight = value;
                }

            }

        }

    }

}
