//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for legend complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="legend">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}infoblock">
 *       &lt;sequence>
 *         &lt;element name="Legend.Caption" type="{http://www.prognoz.ru/Adhoc}tag.caption"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.prognoz.ru/Adhoc}Orientation"/>
 *       &lt;attribute name="Source" use="required" type="{http://www.prognoz.ru/Adhoc}idType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "legend", propOrder = {
    "legendCaption"
})
public class Legend
    extends Infoblock
{

    @XmlElement(name = "Legend.Caption", required = true)
    protected TagCaption legendCaption;
    @XmlAttribute(name = "Orientation", namespace = "http://www.prognoz.ru/Adhoc")
    protected String orientation;
    @XmlAttribute(name = "Source", required = true)
    protected String source;

    /**
     * Gets the value of the legendCaption property.
     * 
     * @return
     *     possible object is
     *     {@link TagCaption }
     *     
     */
    public TagCaption getLegendCaption() {
        return legendCaption;
    }

    /**
     * Sets the value of the legendCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagCaption }
     *     
     */
    public void setLegendCaption(TagCaption value) {
        this.legendCaption = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrientation() {
        if (orientation == null) {
            return "Vertical";
        } else {
            return orientation;
        }
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrientation(String value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

}
