//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for obj complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="obj">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Id" type="{http://www.prognoz.ru/Adhoc}idType" />
 *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MinWidth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MinHeight" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Margin" type="{http://www.w3.org/2001/XMLSchema}string" default="0,0,0,0" />
 *       &lt;attribute name="ShowHeader" type="{http://www.prognoz.ru/Adhoc}bool" default="true" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Visible" type="{http://www.prognoz.ru/Adhoc}bool" default="true" />
 *       &lt;attribute name="Grid.Row" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Grid.Column" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Grid.ColSpan" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Grid.RowSpan" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DockPanel.Dock">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Left"/>
 *             &lt;enumeration value="Right"/>
 *             &lt;enumeration value="Top"/>
 *             &lt;enumeration value="Bottom"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SplitPanel.Position">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="First"/>
 *             &lt;enumeration value="Last"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VerticalAlignment" default="Stretch">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Top"/>
 *             &lt;enumeration value="Center"/>
 *             &lt;enumeration value="Bottom"/>
 *             &lt;enumeration value="Stretch"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="HorizontalAlignment" default="Stretch">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Left"/>
 *             &lt;enumeration value="Center"/>
 *             &lt;enumeration value="Right"/>
 *             &lt;enumeration value="Stretch"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obj")
@XmlSeeAlso({
    Themes.Theme.class,
    Themes.class,
    ContainerBasePropertiesBinding.PropertiesBinding.Binding.class,
    ContainerBasePropertiesBinding.PropertiesBinding.class,
    ContainerBasePropertiesBinding.class,
    Obstyle.class,
    MenuItem.class,
    ControlItem.class,
    by.prognoz.exjaxb.test.adhoc.Frame.FrameCaption.Caption.class,
    View.class,
    Grid.class,
    ContainerBase.class,
    Control.class,
    Infoblock.class,
    by.prognoz.exjaxb.test.adhoc.TagCaption.Caption.class
})
public class Obj {

    @XmlAttribute(name = "Id")
    protected String id;
    @XmlAttribute(name = "Width")
    protected String width;
    @XmlAttribute(name = "Height")
    protected String height;
    @XmlAttribute(name = "MinWidth")
    protected String minWidth;
    @XmlAttribute(name = "MinHeight")
    protected String minHeight;
    @XmlAttribute(name = "Margin")
    protected String margin;
    @XmlAttribute(name = "ShowHeader")
    protected String showHeader;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "Description")
    protected String description;
    @XmlAttribute(name = "Visible")
    protected String visible;
    @XmlAttribute(name = "Grid.Row")
    protected BigInteger gridRow;
    @XmlAttribute(name = "Grid.Column")
    protected BigInteger gridColumn;
    @XmlAttribute(name = "Grid.ColSpan")
    protected BigInteger gridColSpan;
    @XmlAttribute(name = "Grid.RowSpan")
    protected BigInteger gridRowSpan;
    @XmlAttribute(name = "DockPanel.Dock")
    protected String dockPanelDock;
    @XmlAttribute(name = "SplitPanel.Position")
    protected String splitPanelPosition;
    @XmlAttribute(name = "VerticalAlignment")
    protected String verticalAlignment;
    @XmlAttribute(name = "HorizontalAlignment")
    protected String horizontalAlignment;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the minWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinWidth() {
        return minWidth;
    }

    /**
     * Sets the value of the minWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinWidth(String value) {
        this.minWidth = value;
    }

    /**
     * Gets the value of the minHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinHeight() {
        return minHeight;
    }

    /**
     * Sets the value of the minHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinHeight(String value) {
        this.minHeight = value;
    }

    /**
     * Gets the value of the margin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMargin() {
        if (margin == null) {
            return "0,0,0,0";
        } else {
            return margin;
        }
    }

    /**
     * Sets the value of the margin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMargin(String value) {
        this.margin = value;
    }

    /**
     * Gets the value of the showHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowHeader() {
        if (showHeader == null) {
            return "true";
        } else {
            return showHeader;
        }
    }

    /**
     * Sets the value of the showHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowHeader(String value) {
        this.showHeader = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        if (visible == null) {
            return "true";
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the gridRow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGridRow() {
        return gridRow;
    }

    /**
     * Sets the value of the gridRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGridRow(BigInteger value) {
        this.gridRow = value;
    }

    /**
     * Gets the value of the gridColumn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGridColumn() {
        return gridColumn;
    }

    /**
     * Sets the value of the gridColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGridColumn(BigInteger value) {
        this.gridColumn = value;
    }

    /**
     * Gets the value of the gridColSpan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGridColSpan() {
        return gridColSpan;
    }

    /**
     * Sets the value of the gridColSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGridColSpan(BigInteger value) {
        this.gridColSpan = value;
    }

    /**
     * Gets the value of the gridRowSpan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGridRowSpan() {
        return gridRowSpan;
    }

    /**
     * Sets the value of the gridRowSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGridRowSpan(BigInteger value) {
        this.gridRowSpan = value;
    }

    /**
     * Gets the value of the dockPanelDock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDockPanelDock() {
        return dockPanelDock;
    }

    /**
     * Sets the value of the dockPanelDock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDockPanelDock(String value) {
        this.dockPanelDock = value;
    }

    /**
     * Gets the value of the splitPanelPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplitPanelPosition() {
        return splitPanelPosition;
    }

    /**
     * Sets the value of the splitPanelPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplitPanelPosition(String value) {
        this.splitPanelPosition = value;
    }

    /**
     * Gets the value of the verticalAlignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalAlignment() {
        if (verticalAlignment == null) {
            return "Stretch";
        } else {
            return verticalAlignment;
        }
    }

    /**
     * Sets the value of the verticalAlignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalAlignment(String value) {
        this.verticalAlignment = value;
    }

    /**
     * Gets the value of the horizontalAlignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalAlignment() {
        if (horizontalAlignment == null) {
            return "Stretch";
        } else {
            return horizontalAlignment;
        }
    }

    /**
     * Sets the value of the horizontalAlignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalAlignment(String value) {
        this.horizontalAlignment = value;
    }

}
