//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.prognoz.exjaxb.test.adhoc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.prognoz.exjaxb.test.adhoc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Adhoc_QNAME = new QName("http://www.prognoz.ru/Adhoc", "Adhoc");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.prognoz.exjaxb.test.adhoc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DsMssql }
     * 
     */
    public DsMssql createDsMssql() {
        return new DsMssql();
    }

    /**
     * Create an instance of {@link RadioButton }
     * 
     */
    public RadioButton createRadioButton() {
        return new RadioButton();
    }

    /**
     * Create an instance of {@link SplitPanel.SplitPanelPartDefinitions.PartDefinitions.FirstPartDefinition }
     * 
     */
    public SplitPanel.SplitPanelPartDefinitions.PartDefinitions.FirstPartDefinition createSplitPanelSplitPanelPartDefinitionsPartDefinitionsFirstPartDefinition() {
        return new SplitPanel.SplitPanelPartDefinitions.PartDefinitions.FirstPartDefinition();
    }

    /**
     * Create an instance of {@link CheckBox.CheckBoxEventHandlers.EventHandlers }
     * 
     */
    public CheckBox.CheckBoxEventHandlers.EventHandlers createCheckBoxCheckBoxEventHandlersEventHandlers() {
        return new CheckBox.CheckBoxEventHandlers.EventHandlers();
    }

    /**
     * Create an instance of {@link Button }
     * 
     */
    public Button createButton() {
        return new Button();
    }

    /**
     * Create an instance of {@link Button.ButtonEventHandlers.EventHandlers }
     * 
     */
    public Button.ButtonEventHandlers.EventHandlers createButtonButtonEventHandlersEventHandlers() {
        return new Button.ButtonEventHandlers.EventHandlers();
    }

    /**
     * Create an instance of {@link Grid.GridColumnDefinitions }
     * 
     */
    public Grid.GridColumnDefinitions createGridGridColumnDefinitions() {
        return new Grid.GridColumnDefinitions();
    }

    /**
     * Create an instance of {@link ContainerBasePropertiesBinding.PropertiesBinding }
     * 
     */
    public ContainerBasePropertiesBinding.PropertiesBinding createContainerBasePropertiesBindingPropertiesBinding() {
        return new ContainerBasePropertiesBinding.PropertiesBinding();
    }

    /**
     * Create an instance of {@link Grid.GridColumnDefinitions.ColumnDefinitions }
     * 
     */
    public Grid.GridColumnDefinitions.ColumnDefinitions createGridGridColumnDefinitionsColumnDefinitions() {
        return new Grid.GridColumnDefinitions.ColumnDefinitions();
    }

    /**
     * Create an instance of {@link ConnectOra }
     * 
     */
    public ConnectOra createConnectOra() {
        return new ConnectOra();
    }

    /**
     * Create an instance of {@link ScrollViewer }
     * 
     */
    public ScrollViewer createScrollViewer() {
        return new ScrollViewer();
    }

    /**
     * Create an instance of {@link Toolbar }
     * 
     */
    public Toolbar createToolbar() {
        return new Toolbar();
    }

    /**
     * Create an instance of {@link InfoblockVisualizers.Visualizers.FusionChartVisualizer }
     * 
     */
    public InfoblockVisualizers.Visualizers.FusionChartVisualizer createInfoblockVisualizersVisualizersFusionChartVisualizer() {
        return new InfoblockVisualizers.Visualizers.FusionChartVisualizer();
    }

    /**
     * Create an instance of {@link PageControl.PageControlPages.Pages }
     * 
     */
    public PageControl.PageControlPages.Pages createPageControlPageControlPagesPages() {
        return new PageControl.PageControlPages.Pages();
    }

    /**
     * Create an instance of {@link Grid.GridRowDefinitions.RowDefinitions.RowDefinition }
     * 
     */
    public Grid.GridRowDefinitions.RowDefinitions.RowDefinition createGridGridRowDefinitionsRowDefinitionsRowDefinition() {
        return new Grid.GridRowDefinitions.RowDefinitions.RowDefinition();
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link RadioButton.RadioButtonEventHandlers.EventHandlers }
     * 
     */
    public RadioButton.RadioButtonEventHandlers.EventHandlers createRadioButtonRadioButtonEventHandlersEventHandlers() {
        return new RadioButton.RadioButtonEventHandlers.EventHandlers();
    }

    /**
     * Create an instance of {@link ComboBox.ComboBoxItems.Items }
     * 
     */
    public ComboBox.ComboBoxItems.Items createComboBoxComboBoxItemsItems() {
        return new ComboBox.ComboBoxItems.Items();
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link DsP5Expressreport }
     * 
     */
    public DsP5Expressreport createDsP5Expressreport() {
        return new DsP5Expressreport();
    }

    /**
     * Create an instance of {@link View }
     * 
     */
    public View createView() {
        return new View();
    }

    /**
     * Create an instance of {@link GenericVisualizer }
     * 
     */
    public GenericVisualizer createGenericVisualizer() {
        return new GenericVisualizer();
    }

    /**
     * Create an instance of {@link ContainerBasePropertiesBinding.PropertiesBinding.Binding }
     * 
     */
    public ContainerBasePropertiesBinding.PropertiesBinding.Binding createContainerBasePropertiesBindingPropertiesBindingBinding() {
        return new ContainerBasePropertiesBinding.PropertiesBinding.Binding();
    }

    /**
     * Create an instance of {@link Themes }
     * 
     */
    public Themes createThemes() {
        return new Themes();
    }

    /**
     * Create an instance of {@link DialogContainer }
     * 
     */
    public DialogContainer createDialogContainer() {
        return new DialogContainer();
    }

    /**
     * Create an instance of {@link Menu }
     * 
     */
    public Menu createMenu() {
        return new Menu();
    }

    /**
     * Create an instance of {@link MenuItem.MenuItemEventHandlers.EventHandlers }
     * 
     */
    public MenuItem.MenuItemEventHandlers.EventHandlers createMenuItemMenuItemEventHandlersEventHandlers() {
        return new MenuItem.MenuItemEventHandlers.EventHandlers();
    }

    /**
     * Create an instance of {@link MenuItem.MenuItemEventHandlers }
     * 
     */
    public MenuItem.MenuItemEventHandlers createMenuItemMenuItemEventHandlers() {
        return new MenuItem.MenuItemEventHandlers();
    }

    /**
     * Create an instance of {@link PageControl.PageControlPages }
     * 
     */
    public PageControl.PageControlPages createPageControlPageControlPages() {
        return new PageControl.PageControlPages();
    }

    /**
     * Create an instance of {@link CheckBox }
     * 
     */
    public CheckBox createCheckBox() {
        return new CheckBox();
    }

    /**
     * Create an instance of {@link TagCaption.Caption }
     * 
     */
    public TagCaption.Caption createTagCaptionCaption() {
        return new TagCaption.Caption();
    }

    /**
     * Create an instance of {@link RadioButton.RadioButtonEventHandlers }
     * 
     */
    public RadioButton.RadioButtonEventHandlers createRadioButtonRadioButtonEventHandlers() {
        return new RadioButton.RadioButtonEventHandlers();
    }

    /**
     * Create an instance of {@link ControlItem }
     * 
     */
    public ControlItem createControlItem() {
        return new ControlItem();
    }

    /**
     * Create an instance of {@link Report.ReportViews }
     * 
     */
    public Report.ReportViews createReportReportViews() {
        return new Report.ReportViews();
    }

    /**
     * Create an instance of {@link Report.ReportViews.Views }
     * 
     */
    public Report.ReportViews.Views createReportReportViewsViews() {
        return new Report.ReportViews.Views();
    }

    /**
     * Create an instance of {@link Grid.GridRowDefinitions.RowDefinitions }
     * 
     */
    public Grid.GridRowDefinitions.RowDefinitions createGridGridRowDefinitionsRowDefinitions() {
        return new Grid.GridRowDefinitions.RowDefinitions();
    }

    /**
     * Create an instance of {@link DsP5ExpressreportParamlist }
     * 
     */
    public DsP5ExpressreportParamlist createDsP5ExpressreportParamlist() {
        return new DsP5ExpressreportParamlist();
    }

    /**
     * Create an instance of {@link ConnectMssql }
     * 
     */
    public ConnectMssql createConnectMssql() {
        return new ConnectMssql();
    }

    /**
     * Create an instance of {@link ContainerBase }
     * 
     */
    public ContainerBase createContainerBase() {
        return new ContainerBase();
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link Obj }
     * 
     */
    public Obj createObj() {
        return new Obj();
    }

    /**
     * Create an instance of {@link TabControl }
     * 
     */
    public TabControl createTabControl() {
        return new TabControl();
    }

    /**
     * Create an instance of {@link InfoblockVisualizers.Visualizers }
     * 
     */
    public InfoblockVisualizers.Visualizers createInfoblockVisualizersVisualizers() {
        return new InfoblockVisualizers.Visualizers();
    }

    /**
     * Create an instance of {@link Frame }
     * 
     */
    public Frame createFrame() {
        return new Frame();
    }

    /**
     * Create an instance of {@link Adhocroot }
     * 
     */
    public Adhocroot createAdhocroot() {
        return new Adhocroot();
    }

    /**
     * Create an instance of {@link SplitPanel.SplitPanelPartDefinitions.PartDefinitions.LastPartDefinition }
     * 
     */
    public SplitPanel.SplitPanelPartDefinitions.PartDefinitions.LastPartDefinition createSplitPanelSplitPanelPartDefinitionsPartDefinitionsLastPartDefinition() {
        return new SplitPanel.SplitPanelPartDefinitions.PartDefinitions.LastPartDefinition();
    }

    /**
     * Create an instance of {@link ComboBox.ComboBoxItems }
     * 
     */
    public ComboBox.ComboBoxItems createComboBoxComboBoxItems() {
        return new ComboBox.ComboBoxItems();
    }

    /**
     * Create an instance of {@link TabControl.TabControlItems.Items }
     * 
     */
    public TabControl.TabControlItems.Items createTabControlTabControlItemsItems() {
        return new TabControl.TabControlItems.Items();
    }

    /**
     * Create an instance of {@link PageControl }
     * 
     */
    public PageControl createPageControl() {
        return new PageControl();
    }

    /**
     * Create an instance of {@link InfoblockVisualizers.Visualizers.FlashMapVisualizer }
     * 
     */
    public InfoblockVisualizers.Visualizers.FlashMapVisualizer createInfoblockVisualizersVisualizersFlashMapVisualizer() {
        return new InfoblockVisualizers.Visualizers.FlashMapVisualizer();
    }

    /**
     * Create an instance of {@link Grid }
     * 
     */
    public Grid createGrid() {
        return new Grid();
    }

    /**
     * Create an instance of {@link StackPanel }
     * 
     */
    public StackPanel createStackPanel() {
        return new StackPanel();
    }

    /**
     * Create an instance of {@link DsParam }
     * 
     */
    public DsParam createDsParam() {
        return new DsParam();
    }

    /**
     * Create an instance of {@link Button.ButtonEventHandlers }
     * 
     */
    public Button.ButtonEventHandlers createButtonButtonEventHandlers() {
        return new Button.ButtonEventHandlers();
    }

    /**
     * Create an instance of {@link InfoblockVisualizers }
     * 
     */
    public InfoblockVisualizers createInfoblockVisualizers() {
        return new InfoblockVisualizers();
    }

    /**
     * Create an instance of {@link SplitPanel }
     * 
     */
    public SplitPanel createSplitPanel() {
        return new SplitPanel();
    }

    /**
     * Create an instance of {@link SplitPanel.SplitPanelPartDefinitions.PartDefinitions }
     * 
     */
    public SplitPanel.SplitPanelPartDefinitions.PartDefinitions createSplitPanelSplitPanelPartDefinitionsPartDefinitions() {
        return new SplitPanel.SplitPanelPartDefinitions.PartDefinitions();
    }

    /**
     * Create an instance of {@link Frame.FrameCaption.Caption }
     * 
     */
    public Frame.FrameCaption.Caption createFrameFrameCaptionCaption() {
        return new Frame.FrameCaption.Caption();
    }

    /**
     * Create an instance of {@link Themes.Theme }
     * 
     */
    public Themes.Theme createThemesTheme() {
        return new Themes.Theme();
    }

    /**
     * Create an instance of {@link SplitPanel.SplitPanelPartDefinitions }
     * 
     */
    public SplitPanel.SplitPanelPartDefinitions createSplitPanelSplitPanelPartDefinitions() {
        return new SplitPanel.SplitPanelPartDefinitions();
    }

    /**
     * Create an instance of {@link InfoblockVisualizers.Visualizers.P5ExpressReportVisualizer }
     * 
     */
    public InfoblockVisualizers.Visualizers.P5ExpressReportVisualizer createInfoblockVisualizersVisualizersP5ExpressReportVisualizer() {
        return new InfoblockVisualizers.Visualizers.P5ExpressReportVisualizer();
    }

    /**
     * Create an instance of {@link DsbParam }
     * 
     */
    public DsbParam createDsbParam() {
        return new DsbParam();
    }

    /**
     * Create an instance of {@link InfoblockVisualizers.Visualizers.P5ProceduralReportVisualizer }
     * 
     */
    public InfoblockVisualizers.Visualizers.P5ProceduralReportVisualizer createInfoblockVisualizersVisualizersP5ProceduralReportVisualizer() {
        return new InfoblockVisualizers.Visualizers.P5ProceduralReportVisualizer();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link TabControl.TabControlItems }
     * 
     */
    public TabControl.TabControlItems createTabControlTabControlItems() {
        return new TabControl.TabControlItems();
    }

    /**
     * Create an instance of {@link DsOra }
     * 
     */
    public DsOra createDsOra() {
        return new DsOra();
    }

    /**
     * Create an instance of {@link MenuItem }
     * 
     */
    public MenuItem createMenuItem() {
        return new MenuItem();
    }

    /**
     * Create an instance of {@link DatePicker }
     * 
     */
    public DatePicker createDatePicker() {
        return new DatePicker();
    }

    /**
     * Create an instance of {@link DsP5Sql }
     * 
     */
    public DsP5Sql createDsP5Sql() {
        return new DsP5Sql();
    }

    /**
     * Create an instance of {@link Dataproviders.DataSources }
     * 
     */
    public Dataproviders.DataSources createDataprovidersDataSources() {
        return new Dataproviders.DataSources();
    }

    /**
     * Create an instance of {@link Dataproviders.Connections }
     * 
     */
    public Dataproviders.Connections createDataprovidersConnections() {
        return new Dataproviders.Connections();
    }

    /**
     * Create an instance of {@link DsDsparams }
     * 
     */
    public DsDsparams createDsDsparams() {
        return new DsDsparams();
    }

    /**
     * Create an instance of {@link Grid.GridColumnDefinitions.ColumnDefinitions.ColumnDefinition }
     * 
     */
    public Grid.GridColumnDefinitions.ColumnDefinitions.ColumnDefinition createGridGridColumnDefinitionsColumnDefinitionsColumnDefinition() {
        return new Grid.GridColumnDefinitions.ColumnDefinitions.ColumnDefinition();
    }

    /**
     * Create an instance of {@link Frame.FrameCaption }
     * 
     */
    public Frame.FrameCaption createFrameFrameCaption() {
        return new Frame.FrameCaption();
    }

    /**
     * Create an instance of {@link DsOraSql }
     * 
     */
    public DsOraSql createDsOraSql() {
        return new DsOraSql();
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link Obstyle }
     * 
     */
    public Obstyle createObstyle() {
        return new Obstyle();
    }

    /**
     * Create an instance of {@link Dataproviders }
     * 
     */
    public Dataproviders createDataproviders() {
        return new Dataproviders();
    }

    /**
     * Create an instance of {@link FrameDataSourceBinding }
     * 
     */
    public FrameDataSourceBinding createFrameDataSourceBinding() {
        return new FrameDataSourceBinding();
    }

    /**
     * Create an instance of {@link ConnectGeneric }
     * 
     */
    public ConnectGeneric createConnectGeneric() {
        return new ConnectGeneric();
    }

    /**
     * Create an instance of {@link CheckBox.CheckBoxEventHandlers }
     * 
     */
    public CheckBox.CheckBoxEventHandlers createCheckBoxCheckBoxEventHandlers() {
        return new CheckBox.CheckBoxEventHandlers();
    }

    /**
     * Create an instance of {@link ComboBox }
     * 
     */
    public ComboBox createComboBox() {
        return new ComboBox();
    }

    /**
     * Create an instance of {@link Infoblock }
     * 
     */
    public Infoblock createInfoblock() {
        return new Infoblock();
    }

    /**
     * Create an instance of {@link DsP5Proceduralreport }
     * 
     */
    public DsP5Proceduralreport createDsP5Proceduralreport() {
        return new DsP5Proceduralreport();
    }

    /**
     * Create an instance of {@link ContainerBasePropertiesBinding }
     * 
     */
    public ContainerBasePropertiesBinding createContainerBasePropertiesBinding() {
        return new ContainerBasePropertiesBinding();
    }

    /**
     * Create an instance of {@link Grid.GridRowDefinitions }
     * 
     */
    public Grid.GridRowDefinitions createGridGridRowDefinitions() {
        return new Grid.GridRowDefinitions();
    }

    /**
     * Create an instance of {@link ConnectP5Mb }
     * 
     */
    public ConnectP5Mb createConnectP5Mb() {
        return new ConnectP5Mb();
    }

    /**
     * Create an instance of {@link FrameDataSourceBinding.DataSourceBinding }
     * 
     */
    public FrameDataSourceBinding.DataSourceBinding createFrameDataSourceBindingDataSourceBinding() {
        return new FrameDataSourceBinding.DataSourceBinding();
    }

    /**
     * Create an instance of {@link DockPanel }
     * 
     */
    public DockPanel createDockPanel() {
        return new DockPanel();
    }

    /**
     * Create an instance of {@link TagCaption }
     * 
     */
    public TagCaption createTagCaption() {
        return new TagCaption();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link DsGeneric }
     * 
     */
    public DsGeneric createDsGeneric() {
        return new DsGeneric();
    }

    /**
     * Create an instance of {@link DsText }
     * 
     */
    public DsText createDsText() {
        return new DsText();
    }

    /**
     * Create an instance of {@link Legend }
     * 
     */
    public Legend createLegend() {
        return new Legend();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Adhocroot }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.prognoz.ru/Adhoc", name = "Adhoc")
    public JAXBElement<Adhocroot> createAdhoc(Adhocroot value) {
        return new JAXBElement<Adhocroot>(_Adhoc_QNAME, Adhocroot.class, null, value);
    }

}
