//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.neosoft.exjaxb.test.adhoc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pageControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pageControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}containerBase">
 *       &lt;sequence>
 *         &lt;element name="PageControl.Pages">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Pages">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Page" type="{http://www.prognoz.ru/Adhoc}containerBase" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PageControl.PropertiesBinding" type="{http://www.prognoz.ru/Adhoc}containerBase.propertiesBinding" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SelectedIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pageControl", propOrder = {
    "pageControlPages",
    "pageControlPropertiesBinding"
})
public class PageControl
    extends ContainerBase
{

    @XmlElement(name = "PageControl.Pages", required = true)
    protected PageControl.PageControlPages pageControlPages;
    @XmlElement(name = "PageControl.PropertiesBinding")
    protected ContainerBasePropertiesBinding pageControlPropertiesBinding;
    @XmlAttribute(name = "SelectedIndex", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger selectedIndex;

    /**
     * Gets the value of the pageControlPages property.
     * 
     * @return
     *     possible object is
     *     {@link PageControl.PageControlPages }
     *     
     */
    public PageControl.PageControlPages getPageControlPages() {
        return pageControlPages;
    }

    /**
     * Sets the value of the pageControlPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageControl.PageControlPages }
     *     
     */
    public void setPageControlPages(PageControl.PageControlPages value) {
        this.pageControlPages = value;
    }

    /**
     * Gets the value of the pageControlPropertiesBinding property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerBasePropertiesBinding }
     *     
     */
    public ContainerBasePropertiesBinding getPageControlPropertiesBinding() {
        return pageControlPropertiesBinding;
    }

    /**
     * Sets the value of the pageControlPropertiesBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerBasePropertiesBinding }
     *     
     */
    public void setPageControlPropertiesBinding(ContainerBasePropertiesBinding value) {
        this.pageControlPropertiesBinding = value;
    }

    /**
     * Gets the value of the selectedIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSelectedIndex() {
        return selectedIndex;
    }

    /**
     * Sets the value of the selectedIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSelectedIndex(BigInteger value) {
        this.selectedIndex = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Pages">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Page" type="{http://www.prognoz.ru/Adhoc}containerBase" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pages"
    })
    public static class PageControlPages {

        @XmlElement(name = "Pages", required = true)
        protected PageControl.PageControlPages.Pages pages;

        /**
         * Gets the value of the pages property.
         * 
         * @return
         *     possible object is
         *     {@link PageControl.PageControlPages.Pages }
         *     
         */
        public PageControl.PageControlPages.Pages getPages() {
            return pages;
        }

        /**
         * Sets the value of the pages property.
         * 
         * @param value
         *     allowed object is
         *     {@link PageControl.PageControlPages.Pages }
         *     
         */
        public void setPages(PageControl.PageControlPages.Pages value) {
            this.pages = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Page" type="{http://www.prognoz.ru/Adhoc}containerBase" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "page"
        })
        public static class Pages {

            @XmlElement(name = "Page", required = true)
            protected List<ContainerBase> page;

            /**
             * Gets the value of the page property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the page property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPage().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ContainerBase }
             * 
             * 
             */
            public List<ContainerBase> getPage() {
                if (page == null) {
                    page = new ArrayList<ContainerBase>();
                }
                return this.page;
            }

        }

    }

}
