//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.neosoft.exjaxb.test.adhoc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for splitPanel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="splitPanel">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}control">
 *       &lt;sequence>
 *         &lt;element name="SplitPanel.PartDefinitions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PartDefinitions" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="FirstPartDefinition">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}string" default="1*" />
 *                                     &lt;attribute name="MinSize" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Collapsed" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="LastPartDefinition">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}string" default="1*" />
 *                                     &lt;attribute name="MinSize" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Collapsed" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ShowSplitter" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
 *       &lt;attribute name="SplitterWidth" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{http://www.prognoz.ru/Adhoc}Orientation"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "splitPanel", propOrder = {
    "splitPanelPartDefinitions"
})
public class SplitPanel
    extends Control
{

    @XmlElement(name = "SplitPanel.PartDefinitions", required = true)
    protected SplitPanel.SplitPanelPartDefinitions splitPanelPartDefinitions;
    @XmlAttribute(name = "Text")
    protected String text;
    @XmlAttribute(name = "ShowSplitter")
    protected String showSplitter;
    @XmlAttribute(name = "SplitterWidth")
    protected String splitterWidth;
    @XmlAttribute(name = "Orientation", namespace = "http://www.prognoz.ru/Adhoc")
    protected String orientation;

    /**
     * Gets the value of the splitPanelPartDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link SplitPanel.SplitPanelPartDefinitions }
     *     
     */
    public SplitPanel.SplitPanelPartDefinitions getSplitPanelPartDefinitions() {
        return splitPanelPartDefinitions;
    }

    /**
     * Sets the value of the splitPanelPartDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitPanel.SplitPanelPartDefinitions }
     *     
     */
    public void setSplitPanelPartDefinitions(SplitPanel.SplitPanelPartDefinitions value) {
        this.splitPanelPartDefinitions = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the showSplitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowSplitter() {
        if (showSplitter == null) {
            return "false";
        } else {
            return showSplitter;
        }
    }

    /**
     * Sets the value of the showSplitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowSplitter(String value) {
        this.showSplitter = value;
    }

    /**
     * Gets the value of the splitterWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplitterWidth() {
        return splitterWidth;
    }

    /**
     * Sets the value of the splitterWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplitterWidth(String value) {
        this.splitterWidth = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrientation() {
        if (orientation == null) {
            return "Vertical";
        } else {
            return orientation;
        }
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrientation(String value) {
        this.orientation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PartDefinitions" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="FirstPartDefinition">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}string" default="1*" />
     *                           &lt;attribute name="MinSize" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Collapsed" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="LastPartDefinition">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}string" default="1*" />
     *                           &lt;attribute name="MinSize" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Collapsed" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partDefinitions"
    })
    public static class SplitPanelPartDefinitions {

        @XmlElement(name = "PartDefinitions", required = true)
        protected List<SplitPanel.SplitPanelPartDefinitions.PartDefinitions> partDefinitions;

        /**
         * Gets the value of the partDefinitions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the partDefinitions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPartDefinitions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SplitPanel.SplitPanelPartDefinitions.PartDefinitions }
         * 
         * 
         */
        public List<SplitPanel.SplitPanelPartDefinitions.PartDefinitions> getPartDefinitions() {
            if (partDefinitions == null) {
                partDefinitions = new ArrayList<SplitPanel.SplitPanelPartDefinitions.PartDefinitions>();
            }
            return this.partDefinitions;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="FirstPartDefinition">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}string" default="1*" />
         *                 &lt;attribute name="MinSize" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Collapsed" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="LastPartDefinition">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}string" default="1*" />
         *                 &lt;attribute name="MinSize" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Collapsed" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class PartDefinitions {

            @XmlElement(name = "FirstPartDefinition", required = true)
            protected SplitPanel.SplitPanelPartDefinitions.PartDefinitions.FirstPartDefinition firstPartDefinition;
            @XmlElement(name = "LastPartDefinition", required = true)
            protected SplitPanel.SplitPanelPartDefinitions.PartDefinitions.LastPartDefinition lastPartDefinition;

            /**
             * Gets the value of the firstPartDefinition property.
             * 
             * @return
             *     possible object is
             *     {@link SplitPanel.SplitPanelPartDefinitions.PartDefinitions.FirstPartDefinition }
             *     
             */
            public SplitPanel.SplitPanelPartDefinitions.PartDefinitions.FirstPartDefinition getFirstPartDefinition() {
                return firstPartDefinition;
            }

            /**
             * Sets the value of the firstPartDefinition property.
             * 
             * @param value
             *     allowed object is
             *     {@link SplitPanel.SplitPanelPartDefinitions.PartDefinitions.FirstPartDefinition }
             *     
             */
            public void setFirstPartDefinition(SplitPanel.SplitPanelPartDefinitions.PartDefinitions.FirstPartDefinition value) {
                this.firstPartDefinition = value;
            }

            /**
             * Gets the value of the lastPartDefinition property.
             * 
             * @return
             *     possible object is
             *     {@link SplitPanel.SplitPanelPartDefinitions.PartDefinitions.LastPartDefinition }
             *     
             */
            public SplitPanel.SplitPanelPartDefinitions.PartDefinitions.LastPartDefinition getLastPartDefinition() {
                return lastPartDefinition;
            }

            /**
             * Sets the value of the lastPartDefinition property.
             * 
             * @param value
             *     allowed object is
             *     {@link SplitPanel.SplitPanelPartDefinitions.PartDefinitions.LastPartDefinition }
             *     
             */
            public void setLastPartDefinition(SplitPanel.SplitPanelPartDefinitions.PartDefinitions.LastPartDefinition value) {
                this.lastPartDefinition = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}string" default="1*" />
             *       &lt;attribute name="MinSize" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Collapsed" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class FirstPartDefinition {

                @XmlAttribute(name = "Size")
                protected String size;
                @XmlAttribute(name = "MinSize")
                protected String minSize;
                @XmlAttribute(name = "Collapsed")
                protected String collapsed;

                /**
                 * Gets the value of the size property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSize() {
                    if (size == null) {
                        return "1*";
                    } else {
                        return size;
                    }
                }

                /**
                 * Sets the value of the size property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSize(String value) {
                    this.size = value;
                }

                /**
                 * Gets the value of the minSize property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinSize() {
                    return minSize;
                }

                /**
                 * Sets the value of the minSize property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinSize(String value) {
                    this.minSize = value;
                }

                /**
                 * Gets the value of the collapsed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCollapsed() {
                    if (collapsed == null) {
                        return "false";
                    } else {
                        return collapsed;
                    }
                }

                /**
                 * Sets the value of the collapsed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCollapsed(String value) {
                    this.collapsed = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Size" type="{http://www.w3.org/2001/XMLSchema}string" default="1*" />
             *       &lt;attribute name="MinSize" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Collapsed" type="{http://www.prognoz.ru/Adhoc}bool" default="false" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class LastPartDefinition {

                @XmlAttribute(name = "Size")
                protected String size;
                @XmlAttribute(name = "MinSize")
                protected String minSize;
                @XmlAttribute(name = "Collapsed")
                protected String collapsed;

                /**
                 * Gets the value of the size property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSize() {
                    if (size == null) {
                        return "1*";
                    } else {
                        return size;
                    }
                }

                /**
                 * Sets the value of the size property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSize(String value) {
                    this.size = value;
                }

                /**
                 * Gets the value of the minSize property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMinSize() {
                    return minSize;
                }

                /**
                 * Sets the value of the minSize property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMinSize(String value) {
                    this.minSize = value;
                }

                /**
                 * Gets the value of the collapsed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCollapsed() {
                    if (collapsed == null) {
                        return "false";
                    } else {
                        return collapsed;
                    }
                }

                /**
                 * Sets the value of the collapsed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCollapsed(String value) {
                    this.collapsed = value;
                }

            }

        }

    }

}
