//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.neosoft.exjaxb.test.adhoc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tabControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tabControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}control">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="TabControl.PropertiesBinding" type="{http://www.prognoz.ru/Adhoc}containerBase.propertiesBinding"/>
 *         &lt;element name="TabControl.Items">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Items">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TabControlItem" type="{http://www.prognoz.ru/Adhoc}controlItem" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SelectedIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tabControl", propOrder = {
    "tabControlPropertiesBinding",
    "tabControlItems"
})
public class TabControl
    extends Control
{

    @XmlElement(name = "TabControl.PropertiesBinding")
    protected ContainerBasePropertiesBinding tabControlPropertiesBinding;
    @XmlElement(name = "TabControl.Items")
    protected TabControl.TabControlItems tabControlItems;
    @XmlAttribute(name = "SelectedIndex", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger selectedIndex;

    /**
     * Gets the value of the tabControlPropertiesBinding property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerBasePropertiesBinding }
     *     
     */
    public ContainerBasePropertiesBinding getTabControlPropertiesBinding() {
        return tabControlPropertiesBinding;
    }

    /**
     * Sets the value of the tabControlPropertiesBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerBasePropertiesBinding }
     *     
     */
    public void setTabControlPropertiesBinding(ContainerBasePropertiesBinding value) {
        this.tabControlPropertiesBinding = value;
    }

    /**
     * Gets the value of the tabControlItems property.
     * 
     * @return
     *     possible object is
     *     {@link TabControl.TabControlItems }
     *     
     */
    public TabControl.TabControlItems getTabControlItems() {
        return tabControlItems;
    }

    /**
     * Sets the value of the tabControlItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link TabControl.TabControlItems }
     *     
     */
    public void setTabControlItems(TabControl.TabControlItems value) {
        this.tabControlItems = value;
    }

    /**
     * Gets the value of the selectedIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSelectedIndex() {
        return selectedIndex;
    }

    /**
     * Sets the value of the selectedIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSelectedIndex(BigInteger value) {
        this.selectedIndex = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Items">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TabControlItem" type="{http://www.prognoz.ru/Adhoc}controlItem" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "items"
    })
    public static class TabControlItems {

        @XmlElement(name = "Items", required = true)
        protected TabControl.TabControlItems.Items items;

        /**
         * Gets the value of the items property.
         * 
         * @return
         *     possible object is
         *     {@link TabControl.TabControlItems.Items }
         *     
         */
        public TabControl.TabControlItems.Items getItems() {
            return items;
        }

        /**
         * Sets the value of the items property.
         * 
         * @param value
         *     allowed object is
         *     {@link TabControl.TabControlItems.Items }
         *     
         */
        public void setItems(TabControl.TabControlItems.Items value) {
            this.items = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TabControlItem" type="{http://www.prognoz.ru/Adhoc}controlItem" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tabControlItem"
        })
        public static class Items {

            @XmlElement(name = "TabControlItem")
            protected List<ControlItem> tabControlItem;

            /**
             * Gets the value of the tabControlItem property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tabControlItem property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTabControlItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ControlItem }
             * 
             * 
             */
            public List<ControlItem> getTabControlItem() {
                if (tabControlItem == null) {
                    tabControlItem = new ArrayList<ControlItem>();
                }
                return this.tabControlItem;
            }

        }

    }

}
