//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 10:39:14 AM EEST 
//


package by.neosoft.exjaxb.test.adhoc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for themes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="themes">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
 *       &lt;sequence>
 *         &lt;element name="Theme" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
 *                 &lt;sequence>
 *                   &lt;element name="ObjectStyle" type="{http://www.prognoz.ru/Adhoc}obstyle" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="DefaultStyleId" type="{http://www.prognoz.ru/Adhoc}bool" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "themes", propOrder = {
    "theme"
})
public class Themes
    extends Obj
{

    @XmlElement(name = "Theme", required = true)
    protected List<Themes.Theme> theme;

    /**
     * Gets the value of the theme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Themes.Theme }
     * 
     * 
     */
    public List<Themes.Theme> getTheme() {
        if (theme == null) {
            theme = new ArrayList<Themes.Theme>();
        }
        return this.theme;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.prognoz.ru/Adhoc}obj">
     *       &lt;sequence>
     *         &lt;element name="ObjectStyle" type="{http://www.prognoz.ru/Adhoc}obstyle" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="DefaultStyleId" type="{http://www.prognoz.ru/Adhoc}bool" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "objectStyle"
    })
    public static class Theme
        extends Obj
    {

        @XmlElement(name = "ObjectStyle", required = true)
        protected List<Obstyle> objectStyle;
        @XmlAttribute(name = "DefaultStyleId")
        protected String defaultStyleId;

        /**
         * Gets the value of the objectStyle property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the objectStyle property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObjectStyle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Obstyle }
         * 
         * 
         */
        public List<Obstyle> getObjectStyle() {
            if (objectStyle == null) {
                objectStyle = new ArrayList<Obstyle>();
            }
            return this.objectStyle;
        }

        /**
         * Gets the value of the defaultStyleId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultStyleId() {
            return defaultStyleId;
        }

        /**
         * Sets the value of the defaultStyleId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultStyleId(String value) {
            this.defaultStyleId = value;
        }

    }

}
