//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.22 at 04:22:11 PM FET 
//

package by.neosoft.iframework.example.shared.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.google.gwt.user.client.rpc.IsSerializable;

/**
 * <p>
 * Java class for config complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="entryPoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" fixed="0.1-SNAPSHOT" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author alex oreshkevich
 */
@XmlRootElement(name = "config")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "config", propOrder = {

})
public class Config implements IsSerializable {

  @XmlElement(required = true)
  protected String entryPoint;

  @XmlAttribute(name = "version")
  protected String version;

  public Config() {
  }

  /**
   * Gets the value of the entryPoint property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEntryPoint() {
    return entryPoint;
  }

  /**
   * Sets the value of the entryPoint property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setEntryPoint(String value) {
    this.entryPoint = value;
  }

  /**
   * Gets the value of the version property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getVersion() {
    if (version == null) {
      return "0.1-SNAPSHOT";
    }
    else {
      return version;
    }
  }

  /**
   * Sets the value of the version property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setVersion(String value) {
    this.version = value;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    builder.append("Config [entryPoint=");
    builder.append(getEntryPoint());
    builder.append(", version=");
    builder.append(getVersion());
    builder.append("]");
    return builder.toString();
  }
}
