//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.20 at 11:41:25 AM FET 
//

package by.neosoft.exjaxb.test.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated
 * in the by.neosoft.exjaxb.test.config package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML
 * content. The Java representation of XML content can consist of schema derived interfaces and classes
 * representing the binding of schema type definitions, element declarations and model groups. Factory methods
 * for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _Config_QNAME = new QName("http://www.prognoz.ru/Adhoc", "config");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for
   * package: by.neosoft.exjaxb.test.config
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link Cmjconfig }
   * 
   */
  public Cmjconfig createCmjconfig() {
    return new Cmjconfig();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Cmjconfig }{@code >}
   * 
   */
  @XmlElementDecl(namespace = "http://www.prognoz.ru/Adhoc", name = "config")
  public JAXBElement<Cmjconfig> createConfig(Cmjconfig value) {
    return new JAXBElement<Cmjconfig>(_Config_QNAME, Cmjconfig.class, null, value);
  }

}
