//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.20 at 11:41:25 AM FET 
//

@XmlSchema(
    namespace = "http://www.prognoz.ru/Adhoc",
    elementFormDefault = XmlNsForm.QUALIFIED,
    xmlns = { @XmlNs(prefix = "xsi", namespaceURI = "http://www.prognoz.ru/Adhoc") })
package by.neosoft.exjaxb.test.config;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;

